/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package goodread.library;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lalaAhsan
 */
public class LibProfile extends javax.swing.JFrame {

    /**
     * Creates new form LibProfile
     */
    public LibProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        UserIDLabel1 = new javax.swing.JLabel();
        UserIDLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ViewPro = new javax.swing.JButton();
        ManagePatrons = new javax.swing.JButton();
        ViewBooks = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        ManageBooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(235, 235, 240));
        jPanel2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jPanel2InputMethodTextChanged(evt);
            }
        });

        NameLabel.setBackground(new java.awt.Color(211, 211, 228));
        NameLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 70)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(68, 68, 100));
        NameLabel.setAlignmentX(0.5F);

        UserIDLabel.setBackground(new java.awt.Color(211, 211, 228));
        UserIDLabel.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        UserIDLabel.setForeground(new java.awt.Color(77, 77, 101));
        UserIDLabel.setAlignmentX(0.5F);

        UserIDLabel1.setBackground(new java.awt.Color(211, 211, 228));
        UserIDLabel1.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        UserIDLabel1.setForeground(new java.awt.Color(77, 77, 101));
        UserIDLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserIDLabel1.setText("Your User ID: ");
        UserIDLabel1.setAlignmentX(0.5F);

        UserIDLabel2.setBackground(new java.awt.Color(211, 211, 228));
        UserIDLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 70)); // NOI18N
        UserIDLabel2.setForeground(new java.awt.Color(77, 77, 101));
        UserIDLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UserIDLabel2.setText("Welcome ");
        UserIDLabel2.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(836, 836, 836)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserIDLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UserIDLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UserIDLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(211, 211, 228));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 68, 100));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Task Bar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ViewPro.setBackground(new java.awt.Color(211, 211, 228));
        ViewPro.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        ViewPro.setForeground(new java.awt.Color(77, 77, 101));
        ViewPro.setText("View Profile");
        ViewPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 68, 100), new java.awt.Color(211, 211, 228), new java.awt.Color(68, 68, 100), new java.awt.Color(68, 68, 100)));
        ViewPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProActionPerformed(evt);
            }
        });

        ManagePatrons.setBackground(new java.awt.Color(211, 211, 228));
        ManagePatrons.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        ManagePatrons.setForeground(new java.awt.Color(77, 77, 101));
        ManagePatrons.setText("Manage Patrons");
        ManagePatrons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 68, 100), new java.awt.Color(211, 211, 228), new java.awt.Color(68, 68, 100), new java.awt.Color(68, 68, 100)));
        ManagePatrons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePatronsActionPerformed(evt);
            }
        });

        ViewBooks.setBackground(new java.awt.Color(211, 211, 228));
        ViewBooks.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        ViewBooks.setForeground(new java.awt.Color(77, 77, 101));
        ViewBooks.setText("View Books");
        ViewBooks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 68, 100), new java.awt.Color(211, 211, 228), new java.awt.Color(68, 68, 100), new java.awt.Color(68, 68, 100)));
        ViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBooksActionPerformed(evt);
            }
        });

        LogOut.setBackground(new java.awt.Color(211, 211, 228));
        LogOut.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        LogOut.setForeground(new java.awt.Color(77, 77, 101));
        LogOut.setText("Log out");
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 68, 100), new java.awt.Color(204, 204, 255), new java.awt.Color(68, 68, 100), new java.awt.Color(68, 68, 100)));
        LogOut.setOpaque(true);
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        ManageBooks.setBackground(new java.awt.Color(211, 211, 228));
        ManageBooks.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        ManageBooks.setForeground(new java.awt.Color(68, 68, 100));
        ManageBooks.setText("View Books");
        ManageBooks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(68, 68, 100), new java.awt.Color(230, 235, 240), new java.awt.Color(68, 68, 100), new java.awt.Color(68, 68, 100)));
        ManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(996, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManagePatrons, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewPro, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(459, 459, 459)
                .addComponent(ViewBooks)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewPro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(ManagePatrons, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(LogOut)
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 572, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2InputMethodTextChanged

    private void ViewProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProActionPerformed
        String URL = "jdbc:mysql://localhost:3306/GoodRead";
        String username = "root";
        String password = "Radhika1@";
        int userID = Integer.parseInt(UserIDLabel.getText());
        String query = "SELECT * FROM librarian WHERE LibrarianID=?";

        Connection connect = null;
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            connect = DriverManager.getConnection(URL, username, password);
            stmt = connect.prepareStatement(query);
            stmt.setInt(1, userID);
            rs = stmt.executeQuery();

            // Assuming ViewProfile is a class that has these fields
            ViewProfile viewProfile = new ViewProfile();

            if (rs.next()) {
                viewProfile.username.setText(rs.getString("Username"));
                viewProfile.password.setText(rs.getString("Password"));
                viewProfile.firstName.setText(rs.getString("FirstName"));
                viewProfile.lastName.setText(rs.getString("SecondName"));
                viewProfile.email.setText(rs.getString("Email"));
                viewProfile.contact.setText(rs.getString("Contact"));
                viewProfile.cnic.setText(rs.getString("CNIC"));
                viewProfile.address.setText(rs.getString("Address"));
                viewProfile.UserID.setText("" + userID);
            } else {
                // Handle case where no matching LibrarianID is found
                JOptionPane.showMessageDialog(null, "No librarian found with ID: " + userID);
            }

            viewProfile.show(); // Consider using setVisible(true) instead of show()
            dispose(); // Dispose of the current frame/window

        } catch (ClassNotFoundException e) {
            System.out.println("JDBC Driver not found: " + e.getMessage());
        } catch (SQLException e) {
            System.out.println("SQL error: " + e.getMessage());
        } finally {
            // Close resources
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (connect != null) {
                    connect.close();
                }
            } catch (SQLException e) {
                System.out.println("Error closing resources: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_ViewProActionPerformed

    private void ManagePatronsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePatronsActionPerformed
        String URL = "jdbc:mysql://localhost:3306/GoodRead";
        String username = "root";
        String password = "Radhika1@";
        String query = "Select * from Patrons";
        ManagePatronsLib managePatrons = new ManagePatronsLib();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try {
            Connection connect = DriverManager.getConnection(URL, username, password);
            PreparedStatement stmt = connect.prepareStatement(query);

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) managePatrons.ManagePatron.getModel();

            while (rs.next()) {
                Object[] row = {rs.getInt("PatronID"),
                    rs.getString("FirstName"),
                    rs.getString("SecondName"),
                    rs.getString("Email"),
                    rs.getString("ContactNum"),
                    rs.getString("Address"),
                    rs.getString("BookTitle"),
                    rs.getTimestamp("borrowDate"),
                    rs.getTimestamp("endDate")};

                model.addRow(row);
            }

            managePatrons.show();
            dispose();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_ManagePatronsActionPerformed

    private void ViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksActionPerformed
        ViewingBooks viewBooks = new ViewingBooks();
        viewBooks.NameLabel2.setText(NameLabel.getText());
        viewBooks.IDLabel2.setText(UserIDLabel.getText());
        String URL = "jdbc:mysql://localhost:3306/GoodRead";
        String username = "root";
        String password = "Radhika1@";
        String query = "Select * from books where available=true";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try {
            Connection connect = DriverManager.getConnection(URL, username, password);

            PreparedStatement stmt = connect.prepareStatement(query);

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) viewBooks.booksTable.getModel();

            while (rs.next()) {

                String BooksTitle = "Book Title: " + rs.getString("BookTitle") + "<br>";
                String specifications = "ID: " + rs.getString("BookID") + "<br>"
                        + "Author Name: " + rs.getString("Author") + "<br>"
                        + "Publisher Name: " + rs.getString("Publisher") + "<br>"
                        + "ISBN NO.: " + rs.getString("ISBN") + "<br>"
                        + "Year: " + rs.getInt("Year") + "<br>"
                        + "Number Of books: " + rs.getInt("NumberOfBooks") + "<br>"
                        + "Status: " + rs.getString("Status");

                Object[] rowData = {BooksTitle + "<html>" + specifications + "</html>"};
                model.addRow(rowData);
            }

            viewBooks.show();
            dispose();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_ViewBooksActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        LogInPage back = new LogInPage();
        back.show();
        dispose();

    }//GEN-LAST:event_LogOutActionPerformed

    private void ManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageBooksActionPerformed
        String URL = "jdbc:mysql://localhost:3306/GoodRead";
        String username = "root";
        String password = "Radhika1@";
        String query = "Select * from books";
        ViewBook managebooks = new ViewBook();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }

        try {
            Connection connect = DriverManager.getConnection(URL, username, password);

            PreparedStatement stmt = connect.prepareStatement(query);

            ResultSet rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) managebooks.manageBooks.getModel();

            while (rs.next()) {

                Object[] rowData = new Object[]{
                    rs.getString("BookID"),
                    rs.getString("BookTitle"),
                    rs.getString("Author"),
                    rs.getString("Publisher"),
                    rs.getString("ISBN"),
                    rs.getInt("Year"),
                    rs.getInt("NumberOfBooks"),
                    rs.getString("Status"),
                    rs.getBoolean("Available")
                };

                model.addRow(rowData);
            }
            dispose();
            managebooks.show();

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ManageBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ManageBooks;
    private javax.swing.JButton ManagePatrons;
    public javax.swing.JLabel NameLabel;
    public javax.swing.JLabel UserIDLabel;
    public javax.swing.JLabel UserIDLabel1;
    public javax.swing.JLabel UserIDLabel2;
    private javax.swing.JButton ViewBooks;
    private javax.swing.JButton ViewPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
